apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app
  template:
    metadata:
      labels:
        app: app
    spec:
      containers:
      - name: app
        image: api-flask-mysql-docker-kubernetes-app:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5001
        envFrom:
        - configMapRef:
            name: app-config
