apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - name: db
        image: mysql:8.0
        ports:
        - containerPort: 3306
        envFrom:
        - configMapRef:
            name: app-config
        env:
          - name: MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                key: password
                name: db-root-pass
      #   volumeMounts:
      #   - name: db-data
      #     mountPath: /var/lib/mysql
      #   - name: db-log
      #     mountPath: /var/log/mysqld.log
      #   - name: db-config
      #     mountPath: /etc/mysql/conf.d/my.cnf
      # volumes:
      # - name: db-data
      #   persistentVolumeClaim:
      #     claimName: db-data-pvc
      # - name: db-log
      #   hostPath:
      #     path: /var/log/mysqld.log
      # - name: db-config
      #   hostPath:
      #     path: /etc/mysql/conf.d/my.cnf
