version: "3.9"

services:
  app:
    container_name: api
    build: .
    ports:
      - "5001:5001"
    depends_on:
      - db
    env_file:
      - .env
    networks:
      - backend

  db:
    container_name: db
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    volumes:
      - ./db/data:/var/lib/mysql
      - ./db/log/mysqld.log:/var/log/mysqld.log
      - ./db/my.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - "${DB_PORT}:${DB_PORT}"
    env_file:
      - .env
    networks:
      - backend

networks:
  backend: