version: "3"
services:
  db:
    container_name: mysql
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: sandbox
      MYSQL_ROOT_PASSWORD: root
      TZ: 'Asia/Tokyo'
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/log/mysqld.log:/var/log/mysqld.log
      - ./mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./mysql/sql:/docker-entrypoint-initdb.d
    networks:
      - backend
  db_admin:
    container_name: phpmyadmin
    image: phpmyadmin:5.2
    depends_on:
      - db
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOSTS=mysql
      - PMA_USER=root
      - PMA_PASSWORD=root
    ports:
      - 8080:80
    networks:
      - backend
  api:
    container_name: node
    build:
      context: ./node
    depends_on:
      - db
    ports:
      - 3000:3000
    volumes:
      - ./node/app:/usr/src/app
    networks:
      - backend
  web:
    container_name: nginx
    image: nginx:1.23.1
    ports:
      - "80:80"
    volumes:
      - ./nginx/templates:/etc/nginx/templates
      - ./nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - api

networks:
  backend:
