version: '3'

services:
  wsgi:
    build: .
    ports:
      - '5001:5001'
    volumes:
      - ./.vscode:/app/.vscode
      - ./app.py:/app/app.py
      - ./wsgi.py:/app/wsgi.py
    command: gunicorn -b 0.0.0.0:5001 wsgi:application --reload