version: '3'

services:
  wsgi:
    build: .
    ports:
      - '5001:5001'
    volumes:
      - ./.vscode:/app/.vscode
      - ./app:/app/app
    command: gunicorn -b 0.0.0.0:5001 app.wsgi:application --reload