apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: http-server-python38-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: http-server-python38
  minReplicas: 3
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
---
apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: http-server-python311-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: http-server-python311
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 50
