apiVersion: v1
kind: Service
metadata:
  name: http-server-python38-service
spec:
  type: NodePort
  selector:
    app: http-server-python38
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
